accounts:
  asoul_bot:

rooms:
  - id: 22625025
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,3D,VUP,向晚,Ava,$name"
    channel_id: 27 
    title: 【A-Soul】向晚 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22625025"
    description: >-
     直播日期: $yy年$mm月$dd日
     向晚【$title】直播录像
     --------------------------------------------------------
     --------------------------------------
     $name
     直播间: https://live.bilibili.com/22625025/
     个人主页: https://space.bilibili.com/672346917/



  - id: 22632424
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,3D,VUP,Bella,贝拉,$name"
    channel_id: 27 
    title: 【A-Soul】贝拉 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22632424"
    description: >-
      直播日期: $yy年$mm月$dd日
      贝拉【$title】直播录像
      --------------------------------------------------------
      --------------------------------------
      $name
      直播间: https://live.bilibili.com/22632424/
      个人主页: https://space.bilibili.com/672353429/
  
  - id: 22634198
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,3D,VUP,Carol,珈乐,$name"
    channel_id: 27 
    title: 【A-Soul】贝拉 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22634198"
    description: >-
      直播日期: $yy年$mm月$dd日
      珈乐【$title】直播录像
      --------------------------------------------------------
      --------------------------------------
      $name
      直播间: https://live.bilibili.com/22634198/
      个人主页: https://space.bilibili.com/351609538/

  - id: 22637261
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,3D,VUP,Diana,嘉然,$name"
    channel_id: 27 
    title: 【A-Soul】嘉然 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22637261"
    description: >-
      直播日期: $yy年$mm月$dd日
      嘉然【$title】直播录像
      --------------------------------------------------------
      --------------------------------------
      $name
      直播间: https://live.bilibili.com/22637261/
      个人主页: https://space.bilibili.com/672328094/
    
  - id: 22625027
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,3D,VUP,Eileen,乃琳,$name"
    channel_id: 27 
    title: 【A-Soul】乃琳 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22625027"
    description: >-
      直播日期: $yy年$mm月$dd日
      乃琳【$title】直播录像
      --------------------------------------------------------
      --------------------------------------
      $name
      直播间: https://live.bilibili.com/22625027/
      个人主页: https://space.bilibili.com/672342685/


  - id: 1107058
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,娜娜捏口俱乐部,夜雨,$name"
    channel_id: 27 
    title: 【娜娜捏口】夜雨 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/1107058"
    description: >-
     直播日期: $yy年$mm月$dd日
     夜雨【$title】直播录像
     --------------------------------------------------------
     --------------------------------------
     $name
     直播间: https://live.bilibili.com/1107058/
     个人主页: https://space.bilibili.com/3178393/

  - id: 22133081
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,BanG Dream!,娜娜捏口俱乐部,废废,$name"
    channel_id: 27 
    title: 【娜娜捏口】废废 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22133081"
    description: >-
     直播日期: $yy年$mm月$dd日
     废废【$title】直播录像
     --------------------------------------------------------
     --------------------------------------
     $name
     直播间: https://live.bilibili.com/22133081/
     个人主页: https://space.bilibili.com/249911313/

  - id: 2751480
    uploader: asoul_bot
    tags: "录播,直播录像,虚拟UP主,三文鱼,$name"
    channel_id: 27 
    title: 【测试】三文鱼 $yy.$mm.$dd $title【直播录像】
    source: "https://live.bilibili.com/22133081"
    description: >-
     直播日期: $yy年$mm月$dd日
     三文鱼【$title】直播录像
     --------------------------------------------------------
     --------------------------------------
     $name
     直播间: https://live.bilibili.com/2751480/
     个人主页: https://space.bilibili.com/13298208/